import Head from 'next/head'
import { Inter } from 'next/font/google'
import Box from '@mui/material/Box'
import Container from '@mui/material/Container'
import Header from '@/components/Home/header/Header'
import NavLinks from '@/components/Home/header/NavLinks'
import MatchesInProgress from '@/components/Home/matches/MatchesInProgress'
import LastUpdates from '@/components/Home/lastUpdates/LastUpdates'
import Ipl from '@/components/Home/ipl/Ipl'
import Footer from '@/components/Home/footer/Footer'
import useMediaQuery from '@mui/material/useMediaQuery'
import BottomNavigationAction from '@mui/material/BottomNavigationAction'
import BottomNavigation from '@mui/material/BottomNavigation'
import { FiHome } from 'react-icons/fi'
import { GiCrossedSabres, GiHamburgerMenu } from 'react-icons/gi'
import { AiOutlineBulb } from 'react-icons/ai'
import { TfiCup } from 'react-icons/tfi'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [navValue, setNavValue] = useState(0)
  const isMobileView = useMediaQuery((theme) =>
    theme.breakpoints.down('tablet')
  )
  return (
    <>
      <Head>
        <title>Cricket</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box component={'main'} className={inter.className}>
        <Header />
        <NavLinks />
        <Container
          sx={{
            minHeight: '100vh',
            py: 6,
          }}
        >
          <MatchesInProgress />
          <LastUpdates />
          <Ipl />
        </Container>
        <Footer />

        {isMobileView && (
          <BottomNavigation
            component={'nav'}
            showLabels
            value={navValue}
            sx={{
              position: 'fixed',
              bottom: 0,
              width: '100%',
              '& svg': {},
            }}
            onChange={(e, v) => {
              setNavValue(v)
              console.log(v)
            }}
          >
            <BottomNavigationAction label='Home' icon={<FiHome />} />
            <BottomNavigationAction
              label='Schedule'
              icon={<GiCrossedSabres />}
            />
            <BottomNavigationAction
              label='Fantasy Tips'
              sx={{
                fontSize: '12px !important',
              }}
              icon={<AiOutlineBulb />}
            />
            <BottomNavigationAction label='Series' icon={<TfiCup />} />
            <BottomNavigationAction label='More' icon={<GiHamburgerMenu />} />
          </BottomNavigation>
        )}
      </Box>
    </>
  )
}
